[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "abacus"
version = "0.0.0"
description = "A tool for analyzing Short Tandem Repeats (STRs) from Long-Read Sequencing data"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Simon Opstrup Drue", email = "simondrue@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "networkx>=3.0",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "pyfaidx",
    "python-levenshtein>=0.26.1",
    "pysam>=0.22.1",
    "rich>=13.7.1",
    "scikit-learn>=1.2.2",
    "scipy>=1.15.2",
    "typer>=0.12.4",
    "pyspoa>=0.2.1",
]

[project.scripts]
abacus = "abacus.main:app"

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
abacus = ["scripts/*.Rmd"]

[tool.pytest.ini_options]
testpaths = ["tests"]
