# Constants
ANCHOR_LEN = 500
MIN_ANCHOR_OVERLAP = 125
MIN_STR_READ_QUAL = 15
MAX_UNLINK_DIST = 50

# For mapping (Minimap2)
# GAP_OPEN_PENALTY = 4
# GAP_EXTENSION_PENALTY = 2
# MISMATCH_PENALTY = 4
# MATCH_SCORE = 2
# LONG_GAP_OPEN_PENALTY = 24
# LONG_GAP_EXTENSION_PENALTY = 1
# N_MISMATCH_PENALTY = 1

# For mapping (my implementation)
GAP_OPEN_PENALTY = 4
GAP_EXTENSION_PENALTY = 2
MISMATCH_PENALTY = 4
MATCH_SCORE = 1
LONG_GAP_OPEN_PENALTY = 24
LONG_GAP_EXTENSION_PENALTY = 1
N_MISMATCH_PENALTY = 1
